build_from:
  aarch64: docker.io/library/python:3.11-slim-bookworm
  amd64: docker.io/library/python:3.11-slim-bookworm
  armhf: docker.io/library/python:3.11-slim-bookworm
  armv7: docker.io/library/python:3.11-slim-bookworm
  i386: docker.io/library/python:3.11-slim-bookworm
